INSERT INTO Menu (name, basePrice) VALUES 
('Classic Milk Tea', 4.50),
('Taro Milk Tea', 4.75),
('Thai Milk Tea', 4.50),
('Honeydew Milk Tea', 4.75),
('Matcha Milk Tea', 4.75),
('Brown Sugar Milk Tea', 5.00),
('Wintermelon Milk Tea', 4.50),
('Oolong Milk Tea', 4.50),
('Jasmine Green Milk Tea', 4.50),
('Earl Grey Milk Tea', 4.50),
('Strawberry Fruit Tea', 4.75),
('Mango Fruit Tea', 4.75),
('Passion Fruit Green Tea', 4.75),
('Lychee Black Tea', 4.75),
('Peach Oolong Tea', 4.75),
('Grapefruit Green Tea', 4.75),
('Lemon Black Tea', 4.50),
('Kiwi Fruit Tea', 4.75),
('Coconut Milk Tea', 4.75),
('Almond Milk Tea', 4.75);
